name: fast-forward
on:
  issue_comment:
    types: [created, edited]
jobs:
  fast-forward:
    # Only run if the comment contains the /fast-forward command.
    if: ${{ contains(github.event.comment.body, '/fast-forward')
            && github.event.issue.pull_request }}
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Check User Permission
        id: check-perm
        uses: actions-cool/check-user-permission@v2.2.0
        with:
          require: write

      - name: Fast forwarding
        if: steps.check-perm.outputs.require-result
        uses: sequoia-pgp/fast-forward@v1
        with:
          merge: true
          comment: on-error
          
